### ISSUE TITLE
Genetic Variants Studies - API endpoint to get all studies resources associated to a given Genetic Variant

### ISSUE THREAD

**Issue by sprintell** [EBISPOT/gwas-ui#283]
As developer
I want an api endpoint
So that when I send a GET request, hateoas, paginated list of all studies associated to a given Genetic Variant in the database is returned in JSON Format

Management Rules:
Rule 1: Endpoint - /v2/variants/{variantId}/studies
Rule 2: HTTP Request Method - GET
Rule 3: HATEOAS, with filer, sorting, pagination, and sizing
Rule 4: Endpoint should accept filter, and sort parameters as in /studies?accession=...&page=0&size=20&sort=...

Rule 5: Search filter should be available for: accession, reported-trait, trait, background-trait, discovery-sample-number, replication-sample-number
Rule 6: Sort feature should be available for: discovery-sample-number, replication-sample-number, association-count, summary-statistics
Rule 7: Returned Study Json entity must include: Study accession, Reported trait, Trait, Background trait, Discovery sample number and ancestry, Replication sample number and ancestry, Association count, and Summary statistics Availability

Acceptance Tests:
Given no parameter
When the front end sends a GET request to the endpoint
Hateoas compliant list of studies is returned in the specified JSON Format

Given sorting, pagination, and/or some search and filter parameters
When the front end sends a GET request to thesame endpoint
Hateoas compliant filtered list of studies satisfying the conditions in the url parameter must be returned

**Comment by sajo-ebi** [comment]
Development almost complete , local testing in progress. Couple of points to be noted

- The API access logic currently is not optimised it checks each study against the sumstats PI GCST list for checking if sumstats is present or not , instead of that we could cache the Sumstats response & check from cache to avoid memory processing, will. implement this at a later point
- 
- On the sorting & searching part w.r.t the Discovery & Replication Sample number unfortunately these fields are not indexed in Solr & are saved as substring of a free text so there is complexity in implementing the search & sort for these , will need changes in Solr schema if we want to implement sort & Search on these fields

**Comment by sajo-ebi** [comment]
@ala-ebi the API details are -:

Uri -> http://gwas-snoopy.ebi.ac.uk:9780/gwas/api/v2/variants/{variantId}/studies

Search fields 
` @JsonProperty("accessionId")
    private String accessionId;

    @JsonProperty("reportedTrait")
    private String reportedTrait;

    @JsonProperty("efoTrait")
    private String efoTrait;

    @JsonProperty("bgTrait")
    private String bgTrait;`

Sort fields  -:

`associationCount
fullPvalueSet`
