### ISSUE TITLE
UI Refactoring API - Solr searching & sorting issues

### ISSUE THREAD

**Issue by sajo-ebi** [EBISPOT/gwas-ui#296]

**Comment by sajo-ebi** [comment]
The below issues have been found w.r.t sorting & searching of some fields as part of moving the pagination & searching from frontend to Backend using Solr -:

- For Studies API we have sort fields Discovery Sample Number & Replication Sample number , both these are part of free text & are in array to enable sorting we need to create two new fields in Solr Storing the aggregated discovery & replication sample numbers then indexing these two fields by running fresh Solr indexing.
- For Association API the field risk frequency is stored as text , to allow sorting we need to clone the field to store as numeric value & reindex Solr & apply sorting on clone field.
- For All API's Reported , EFO & background traits these fields are tokenized & stored to enable searching , hence sorting will not work properly , we need to clone these fields to new fields & store them as String & apply sorting on cloned fields.

**Comment by sajo-ebi** [comment]
- The Highlight Study feature in EFOTrait page will need to be descoped as it needs to pull all studies from Solr  & then sort it by sample size , in 2nd iteration we will be storing sample number as a separate field & then sort the studies based on sample size , this will allow us to implement Highlight study in optimized manner
- The Search for Sample & Ancestry field need to be supported from Solr , the field is not indexed in Solr , we need to enable Solr Indexing for the field & rerun Solr Indexing

**Comment by ljwh2** [comment]
Confirming the main priority is to enable searching and sorting in "Discovery Sample Number" and "Replication sample number" fields. Sort should be by aggregated discovery & replication sample numbers. Note, there are 2 hidden columns "Discovery/Replication sample description". We haven't considered these up till now. The same features should be enabled for those columns if possible.

For the other features mentioned above:

1. Risk allele frequency - current sort functionality seems to work ok for me. Could be because this is always a number <1, so text based sorting gives same results.

2. Sorting by trait fields is not required.

**Comment by sajo-ebi** [comment]
UI changes for Sample fields sorting/filter completed

**Comment by sprintell** [comment]
Done, waiting to be deployed

**Comment by sajo-ebi** [comment]
@ljwh2 the Discovery Sample & Replication Sample sort/search feature is deployed in Dev environment [http://gwas-snoopy.ebi.ac.uk:9780/gwas](http://gwas-snoopy.ebi.ac.uk:9780/gwas), can you ask any curator to test the same

**Comment by ljwh2** [comment]
@eks-ebi could you test this please?

**Comment by eks-ebi** [comment]
Tested this now - sorting works well. Can confirm that it is sorting on the sum of all samples in discovery or replication analyis, not just on the first number in the list, so this is working as intended.
